drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,
    user_id varchar(255),
    password varchar(255),
    nickname varchar(255)
    primary key (id)
);